#!/usr/bin/env bash
# script that:
#	Creates the file /var/run/myscript.pid containing its PID
#	Displays To infinity and beyond indefinitely
#	Displays I hate the kill command when receiving a SIGTERM signal
#	Displays Y U no love me?! when receiving a SIGINT signal
#	Deletes the file /var/run/myscript.pid and terminates itself when
#	receiving a SIGQUIT or SIGTERM signal

# Function to delete the "myscript.pi" file
del() {
	rm -f myscript.pid
	pkill -f 100-process_and_pid_file
}

((a = 0))

# Put the PID into the "myscript.pid" file
echo "$$" > /var/run/myscript.pid

# Display our loop iteration and respond to signals

trap "echo I hate the kill command" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap del SIGQUIT SIGTERM

while ((a == 0)); do
	echo "To infinity and beyond"
	sleep 2
done
