#!/usr/bin/env bash
# This bash (init) script manages the "manage_my_processes" file operations

file_path=/var/run/my_process.pid

if [ "$1" = "start" ];then
    ./manage_my_process &
    echo "$$" > $file_path
    echo "manage_my_process started"
elif [ "$1" = "stop" ];then
    pkill -f ./manage_my_process
    rm $file_path
    echo "manage_my_process stopped"
elif [ "$1" = "restart" ];then
     pkill -f ./manage_my_process
     rm $file_path
     ./manage_my_process &
     echo "$$" > $file_path
     echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
