#!/usr/bin/env bash
# Bash script that displays:
#	"To infinity and beyond" indefinitely
#	With a sleep 2 in between each iteration
#	I am invincible!!! when receiving a SIGTERM signal
((a = 0))

while ((a < 1)); do
	echo "To infinity and beyond"
	trap "echo I am invincible" SIGTERM
	sleep 2
	((a--))

done
