#!/usr/bin/env bash
# This script ells a story based on the contents of the `/etc/passwd` file from prev task

while IFS=':' read username password uid gid info home shell; do
	echo "The user $username is part of the $gid gang,"\
		"lives in $home and rides $shell."\
		"$uid's place is protected by the passcode $password,"\
		"more info about the user here: $info"
done < "/etc/passwd"
