#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code.
#	And then displays this data in OCCURENCE_NUMBER, IP, HTTP_CODE format

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
