#!/usr/bin/env bash
# This script displays "Best School" 10 times, but for the 9th iteration
# it displays "Best School" and then "Hi" on a new line

((count = 0))
while ((count < 10)); do
	echo "Best School"
	((count++))
	if ((count == 9)); then
		echo "Hi"
	fi
done
