#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 20 and
# Displays 4 and then bad luck from China for the 4th loop iteration
# Displays 9 and then bad luck from Japan for the 9th loop iteration
# Displays 17 and then bad luck from Italy for the 17th loop iteration

((count = 0))
while ((count < 20)); do
	((count++))
	case $count in
		4)
			echo $count
			echo "bad luck from China"
			;;
		9)
			echo $count
			echo "bad luck from Japan"
			;;
		17)
			echo $count
			echo "bad luck from Italy"
			;;
		*)
			echo $count
			;;
	esac
done
