#!/usr/bin/env bash
# This script displays the content of the current directory in a list format
# Only the part of the name after the first dash is displayed

for file in *; do
    if [ -f "$file" ] && [ "$file" != "$0" ]; then

        new_name=$(echo "$file" | cut -d'-' -f2-)
        echo "$new_name"
    fi
done
